name: Daily Task

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC

jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print current date and time
        run: |
          echo "This runs every day at midnight (UTC)."
          date -u +"Current UTC time: %Y-%m-%d %H:%M:%S"